name: CI-test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - LICENSE

  pull_request:
    paths-ignore:
      - "**.md"
      - LICENSE

  workflow_dispatch:

jobs:
  lint:
    strategy:
      matrix:
        os-version: ["ubuntu-22.04"]
        python-version: ["3.10"]

    runs-on: ${{ matrix.os-version }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Test
        run: |
          pip install pre-commit

          make lint
